# Supported Funding Model Platforms

github: 
  - monkey-mart
  - monkeymart
  - monkey-mart2
  - monkeymart3

patreon: username

open_collective: collective_name

ko_fi: monkey-mart

tidelift: npm/monkey-mart

community_bridge: monkey-mart

liberapay: monkey-mart

issuehunt: monkey-mart

lfx_crowdfunding: monkey-mart

polar: monkey-mart

buy_me_a_coffee: monkey-mart

thanks_dev: monkey-mart

custom:
  - https://apkitech.com/monkey-mart/
