# Site settings
title: Monkey Mart
description: Welcome to Monkey Mart! Play the best idle management game online.
# Author information
author:
  name: Monkey Mart Game
# Theme settings
remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme

# Markdown settings
markdown: kramdown 
sass:
  style: compressed
